user www-data;
worker_processes   <<WORKER_PROCESSES>> ;
error_log /home/app/webapp/log/error-nginx.log info;

pid /run/nginx.pid;
daemon off;
include /etc/nginx/main.d/*.conf;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections  4048;
    multi_accept on;
    use epoll;
}

worker_rlimit_nofile    200000;

http {
    server_names_hash_bucket_size 128;
    include       mime.types;
    default_type  application/octet-stream;
    limit_conn_log_level warn;

    # Define trusted proxy IP ranges
    set_real_ip_from 0.0.0.0/0;  # Adjust to your proxy's IP ranges
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;

    # Define the log format
    log_format timed_combined '$remote_addr - $remote_user [$time_local] '
                               '"$request" '
                               '$status $body_bytes_sent '
                               '"$http_referer" "$http_user_agent" '
                               '$request_time $upstream_response_time '
                               '$http_x_lang'; 

    sendfile        on;
    tcp_nopush     on;
    tcp_nodelay       on;
    keepalive_timeout  362;
    client_max_body_size    20m;
    client_header_timeout   360;
    client_body_timeout     360;
    fastcgi_read_timeout    360;
    proxy_ignore_client_abort on;
    send_timeout            360;
    lingering_timeout       360;
    open_file_cache max=200000 inactive=60s;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors on;
    reset_timedout_connection on;

    # Gzip settings
    gzip  on;
    gzip_disable "MSIE [1-6]\.(?!.*SV1)";
    gzip_http_version 1.0;
    gzip_comp_level 2;
    gzip_proxied any;
    gzip_types text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript application/json image/bmp image/png image/gif image/jpeg image/jpg;

    # Virtual Host configurations
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
}
