# Expires map
map $sent_http_content_type $expires {
    default off;
    text/html epoch;
    text/css max;
    application/javascript max;
    ~image/ max;
}

# --- HTTP Server Only (Stripped Domain & SSL for Testing) ---
server {
    listen 80;       # 'default_server' forces Nginx to catch all traffic coming to this port
    listen [::]:80;
    
    server_name _;                 # The underscore acts as a catch-all wildcard (ignores specific domains)
    root /home/app/webapp/public;
    index index.php index.html index.htm;

    client_max_body_size 10m;

    error_log /home/app/webapp/log/error.log warn;
    access_log /home/app/webapp/log/access.log timed_combined;

    # Route normal traffic through index.php
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Pass PHP scripts to PHP-FPM
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass 127.0.0.1:9000; 
        fastcgi_read_timeout 180;
    }

    # Static content optimization
    location ~* \.(ico|jpg|gif|png|css|js|swf|html)$ {
        expires $expires;
        add_header Cache-Control "public, no-transform";
    }

    location /nginx_status {
        stub_status on;
        allow 127.0.0.1;
        deny all;
    }

    location ~ \.(aspx|asp) { return 404; }
    location ~ /\.ht { deny all; }
}
